stable:
  evm-type: stable
  fill-params: ''
  solc: 0.8.21
develop:
  evm-type: develop
  fill-params: --until=Prague
  solc: 0.8.21
eip7692:
  evm-type: eip7692
  fill-params: --fork=CancunEIP7692 ./tests/prague
  solc: 0.8.21
eip7692-prague:
  evm-type: eip7692-prague
  fill-params: --fork=PragueEIP7692 ./tests/prague -k "not slow"
  solc: 0.8.21
pectra-devnet-3:
  evm-type: pectra-devnet-3
  fill-params: --fork=Prague -k "not slow and not many_deposits" ./tests/prague/
  solc: 0.8.21